from .zip_upload_only import NODE_CLASS_MAPPINGS as A, NODE_DISPLAY_NAME_MAPPINGS as AN
from .zip_unpack_load_from_path import NODE_CLASS_MAPPINGS as B, NODE_DISPLAY_NAME_MAPPINGS as BN

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(A)
NODE_CLASS_MAPPINGS.update(B)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(AN)
NODE_DISPLAY_NAME_MAPPINGS.update(BN)
