from .nodes import NODE_CLASS_MAPPINGS as _ZIP_NODE_CLASS_MAPPINGS
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as _ZIP_NODE_DISPLAY_NAME_MAPPINGS
from .resize_to_multiple import NODE_CLASS_MAPPINGS as _RESIZE_NODE_CLASS_MAPPINGS
from .resize_to_multiple import NODE_DISPLAY_NAME_MAPPINGS as _RESIZE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **_ZIP_NODE_CLASS_MAPPINGS,
    **_RESIZE_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **_ZIP_NODE_DISPLAY_NAME_MAPPINGS,
    **_RESIZE_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"

